CREATE TABLE `PUBLISHER`(
  `id` int,
  `name` string,
  `countryid` int,
  `phone` string,
  `company` string,
  `street` string,
  `city` string,
  `state` string,
  `zip` string,
  `skype` string,
  `qq` string,
  `desc` string,
  `todayrevenue` double,
  `monthrevenue` double,
  `postback` string,
  `amid` int,
  `todaysendrevenue` double,
  `monthsendrevenue` double,
  `pricepercent` int,
  `token` string,
  `apiconversionpercent` int,
  `apipricepercent` int,
  `uniqueid` string,
  `othersmartlinkcounts` int,
  `isorderbybidprice` int,
  `ampaid` int)
STORED AS ORC;