
-- Hive
 CREATE TABLE tb_demand_account(
   id                            int,
   tb_user_id                    int,
   bd_id                         int,
   am_id                         int,
   name                          string,
   status                        int,
   system_name                   string,
   target_source_token_banner    string,
   target_source_token_native    string,
   target_source_token_video     string,
   target_source_token_audio     string,
   protocol                      int,
   currency                      string,
   balance                       int,
   rtb_version                   string,
   markup_method                 int,
   ad_format                     int,
   secure                        int,
   gzip                          int,
   price_model                   string,
   floor                         int,
   auction_type                  int,
   second_price_subtract_percent int,
   second_price_delta            int,
   notify_price_add_percent      int,
   country                       string,
   country_direction             int,
   os                            int,
   max_qps                       int,
   daily_request_cap             int,
   ip                            string,
   ip_direction                  int,
   publisher                     string,
   publisher_direction           int,
   domain                        string,
   domain_direction              int,
   cat_l1                        string,
   cat                           string,
   cat_direction                 int,
   bundle                        string,
   bundle_direction              int,
   sizes                         string,
   sizes_direction               int,
   device_type                   string,
   media_type                    string
)
STORED AS ORC;


-- Hive
 CREATE TABLE tb_supply_account(
 id	                int,
 tb_user_id	        int,
 bd_id	            int,
 am_id	            int,
 token	            string,
 name	            string,
 status	            int,
 system_name	    string,
 traffic_type	    int,
 protocol	        int,
 profit_percent	    int,
 price_model	    string,
 currency	        string,
 floor	            int,
 decision_source    int,
 secure	            int,
 company	        string,
 domain	            string,
 country	        string,
 address	        string,
 phone	            string,
 skype	            string,
 wechat	            string,
 max_qps	        int,
 daily_request_cap  int
 )
 STORED AS ORC;
--where b_date <'2017-09-10';
